name: Jekyll build for PRs

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Use GH action to build and publish into the gh-pages branch
    - uses: jeffreytse/jekyll-deploy-action@v0.5.0
      with:
        provider: 'github'
        branch: 'gh-pages'
        token: ${{ secrets.GITHUB_TOKEN }}
